spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:${DB_PORT}/${DB_NAME}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update

  jwt:
    secret: ${JWT_SECRET}
    access-token-expiration: 1800000 # 30분
    refresh-token-expiration: 604800000 # 7일

  weather:
    api:
      key: ${WEATHER_API_KEY}


management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  metrics:
    tags:
      application: drift_log
