name: ci.drift_log.yml

# 트리거
on:
  pull_request:
    branches:
      - 'main'
      - 'develop'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Checkout Repository
        uses: actions/checkout@v4

      - name: 2. Setup JDK 21
        uses: actions/setup-java@v4

      - name: 3. Grant excute permission for gradlew
        run: chmod +x drift_log/gradlew

      - name: 4. Gradle Test
        run: cd drift_log  && ./gradlew test
        env:
          SPRING_PROFILES_ACTIVE: test

      - name: 5. Gradle Build & SpotBugs
        run: cd drift_log && ./gradlew build spotbugsMain -x test

      - name: 6. Upload SpotBugs Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: spotbugs-report
          path: drift_log/build/reports/spotbugs/

